'use strict';

const EFFECTS = {
	AbsorbAttribute: { duration: true, magnitude: true },
	AbsorbFatigue: { magnitude: true },
	AbsorbHealth: { magnitude: true },
	AbsorbMagicka: { magnitude: true },
	AbsorbSkill: { duration: true, magnitude: true },
	AlmsiviIntervention: {},
	Blind: { duration: true, magnitude: true },
	BoundBattleAxe: { duration: true },
	BoundBoots: { duration: true },
	BoundCuirass: { duration: true },
	BoundDagger: { duration: true },
	BoundGloves: { duration: true },
	BoundHelm: { duration: true },
	BoundLongbow: { duration: true },
	BoundLongsword: { duration: true },
	BoundMace: { duration: true },
	BoundShield: { duration: true },
	BoundSpear: { duration: true },
	Burden: { duration: true, magnitude: true },
	CalmCreature: { magnitude: true },
	CalmHumanoid: { magnitude: true },
	Chameleon: { duration: true, magnitude: true },
	Charm: { duration: true, magnitude: true },
	CommandCreature: { duration: true, magnitude: true },
	CommandHumanoid: { duration: true, magnitude: true },
	Corprus: { illegal: true },
	CureBlightDisease: {},
	CureCommonDisease: {},
	CureCorprus: { illegal: true },
	CureParalyzation: {},
	CurePoison: {},
	DamageAttribute: { magnitude: true },
	DamageFatigue: { magnitude: true },
	DamageHealth: { magnitude: true },
	DamageMagicka: { magnitude: true },
	DamageSkill: { magnitude: true },
	DemoralizeCreature: { duration: true, magnitude: true },
	DemoralizeHumanoid: { duration: true, magnitude: true },
	DetectAnimal: { duration: true, magnitude: true },
	DetectEnchantment: { duration: true, magnitude: true },
	DetectKey: { duration: true, magnitude: true },
	DisintegrateArmor: { magnitude: true },
	DisintegrateWeapon: { magnitude: true },
	Dispel: { magnitude: true },
	DivineIntervention: {},
	DrainAttribute: { duration: true, magnitude: true },
	DrainFatigue: { duration: true, magnitude: true },
	DrainHealth: { magnitude: true },
	DrainMagicka: { duration: true, magnitude: true },
	DrainSkill: { duration: true, magnitude: true },
	Feather: { duration: true, magnitude: true },
	FireDamage: { magnitude: true },
	FireShield: { duration: true, magnitude: true },
	FortifyAttackBonus: { duration: true, magnitude: true },
	FortifyAttribute: { duration: true, magnitude: true },
	FortifyFatigue: { duration: true, magnitude: true },
	FortifyHealth: { duration: true, magnitude: true },
	FortifyMagicka: { duration: true, magnitude: true },
	FortifyMagickaMultiplier: { duration: true, magnitude: true },
	FortifySkill: { duration: true, magnitude: true },
	FrenzyCreature: { duration: true, magnitude: true },
	FrenzyHumanoid: { duration: true, magnitude: true },
	FrostDamage: { magnitude: true },
	FrostShield: { duration: true, magnitude: true },
	Invisibility: { duration: true, magnitude: true },
	Jump: { duration: true, magnitude: true },
	Levitate: { duration: true, magnitude: true },
	Light: { duration: true, magnitude: true },
	LightningShield: { duration: true, magnitude: true },
	Lock: { magnitude: true },
	Mark: {},
	NightEye: { duration: true, magnitude: true },
	Open: { magnitude: true },
	Paralyze: { duration: 1 },
	Poison: { magnitude: true },
	RallyCreature: { duration: true, magnitude: true },
	RallyHumanoid: { duration: true, magnitude: true },
	Recall: {},
	Reflect: { duration: true, magnitude: true },
	RemoveCurse: { illegal: true },
	ResistBlightDisease: { duration: true, magnitude: true },
	ResistCommonDisease: { duration: true, magnitude: true },
	ResistCorprus: { illegal: true },
	ResistFire: { duration: true, magnitude: true },
	ResistFrost: { duration: true, magnitude: true },
	ResistMagicka: { duration: true, magnitude: true },
	ResistNormalWeapons: { duration: true, magnitude: true },
	ResistParalysis: { duration: true, magnitude: true },
	ResistPoison: { duration: true, magnitude: true },
	ResistShock: { duration: true, magnitude: true },
	RestoreAttribute: { magnitude: true },
	RestoreFatigue: { magnitude: true },
	RestoreHealth: { magnitude: true },
	RestoreMagicka: { magnitude: true },
	RestoreSkill: { magnitude: true },
	Sanctuary: { duration: true, magnitude: true },
	Shield: { duration: true, magnitude: true },
	ShockDamage: { magnitude: true },
	Silence: { duration: true },
	SlowFall: { duration: true, magnitude: true },
	SoulTrap: { duration: true, magnitude: true },
	Sound: { duration: true, magnitude: true },
	SpellAbsorption: { duration: true, magnitude: true },
	StuntedMagicka: {},
	SummonBear: { duration: true },
	SummonBoneWolf: { duration: true },
	SummonBonelord: { duration: true },
	SummonCenturionSphere: { duration: true },
	SummonClannfear: { duration: true },
	SummonDaedroth: { duration: true },
	SummonDremora: { duration: true },
	SummonFabricant: { duration: true },
	SummonFlameAtronach: { duration: true },
	SummonFrostAtronach: { duration: true },
	SummonGhost: { duration: true },
	SummonGoldenSaint: { duration: true },
	SummonGreaterBonewalker: { duration: true },
	SummonHunger: { duration: true },
	SummonLeastBonewalker: { duration: true },
	SummonScamp: { duration: true },
	SummonSkeleton: { duration: true },
	SummonStormAtronach: { duration: true },
	SummonTwilight: { duration: true },
	SummonWolf: { duration: true },
	SunDamage: {},
	SwiftSwim: { duration: true, magnitude: true },
	Telekinesis: { duration: true, magnitude: true },
	TurnUndead: { duration: true, magnitude: true },
	Vampirism: {},
	WaterBreathing: { duration: true, magnitude: true },
	WaterWalking: { duration: true, magnitude: true },
	WeaknessToBlightDisease: { duration: true, magnitude: true },
	WeaknessToCommonDisease: { duration: true, magnitude: true },
	WeaknessToCorprus: { illegal: true },
	WeaknessToFire: { duration: 1, magnitude: true },
	WeaknessToFrost: { duration: 1, magnitude: true },
	WeaknessToMagicka: { duration: 1, magnitude: true },
	WeaknessToNormalWeapons: { duration: true, magnitude: true },
	WeaknessToPoison: { duration: 1, magnitude: true },
	WeaknessToShock: { duration: 1, magnitude: true }
};

function isConstantEffect(record) {
	return record.type === 'Enchantment' && record.data?.enchant_type === 'ConstantEffect'
	|| record.type === 'Spell' && !['Spell', 'Power'].includes(record.data?.spell_type);
}

module.exports = {
	onRecord(record) {
		if(['Alchemy', 'Enchantment', 'Spell'].includes(record.type)) {
			record.effects?.forEach(effect => {
				const checks = EFFECTS[effect.magic_effect];
				if(checks?.illegal) {
					console.log(record.type, record.id, 'uses', effect.magic_effect);
				} else {
					if(checks?.magnitude && (effect.min_magnitude <= 0 && effect.max_magnitude <= 0)) {
						console.log(record.type, record.id, 'uses', effect.magic_effect, 'without a magnitude');
					}
					if(checks?.duration && (effect.duration <= 1 && checks.duration === true || effect.duration < checks.duration) && !isConstantEffect(record)) {
						console.log(record.type, record.id, 'uses', effect.magic_effect, 'with duration', effect.duration);
					}
				}
			});
		}
	}
};
