[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.84"
quote = "^1.0"
syn = { version = "^2.0", features= ["parsing", "printing"] }
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
regex = "^1.10"

[lib]
proc-macro = true
